### ISSUE TITLE
Undefined variable notices

### ISSUE THREAD

**Issue by TLWebdesign** [brianteeman/joomla-cards#3]
Hi, 

First of all thanks for sharing this! 👍 

I just installed this and it seems some variables are always expected to be there. I see two notices:

Warning: Undefined property: stdClass::$image_intro_alt_empty in /root/templates/cassiopeia/html/com_content/category/card_vertical.php on line 19

Warning: Undefined variable $alt in /root/dabo/templates/cassiopeia/html/com_content/category/card_vertical.php on line 27

Figured i open an issue so you know about it.

**Comment by TLWebdesign** [comment]
I changed line 19 to this to fix it. But maybe you know a better fix:

`
$images->image_intro_alt ? $alt = "alt=\"$images->image_intro_alt\"" : $alt = '';
`

**Comment by brianteeman** [comment]
thanks - I will put it on my todo list for this weekend.
Your fix looks correct but I am not at my oc to check

**Comment by brianteeman** [comment]
needed a little more than the code you had. I made a new release. Thanks for reporting it
